### ISSUE TITLE
task作成APIを作る

### ISSUE THREAD

**Issue by campbel2525** [Tamm2/hello_fastapi2#10]
# タスクのゴール
task登録APIを作る
エンドポイントは`post /api/tasks`

# 参考になるもの
ユーザーの新規登録API
ユーザー情報取得API(me api)

# 概要
リクエストは登録に必要なものを送ってもらうようにします
レスポンスは作成されたレコードを返します

(user_idは認証されているで、認証情報から取ってください。)

バリデーションは適切にお願いします
例えば下記のようなもの
```
title: 必須、255文字まで
content: 必須、2000文字まで
deadlined_at: 必須、日時形式
```

リクエストイメージ
```
{
    "title": "タイトル", 
    "content": "プログラミングを理解する", 
    "deadlined_at": "2024-10-01"
}
```

レスポンスのイメージ
```
{
    "id": 1,
    "user_id": 1,
    "title": "タイトル", 
    "content": "プログラミングを理解する", 
    "deadlined_at": "2024-10-01 00:00:00",
    "completed_at": null,
    "created_at": "2024-04-01  00:00:00",
    "updated_at": "2024-10-01  00:00:00",
}
```

# rest apiの概要
今回はrest apiを意識して作って欲しいです
そのため下記のようなエンドポイントになります

httpメソッドは主に
- get
- post
- put
- delete

があります。

それぞれの役割は
- get: 取得系
- post: 新規登録
- put: 更新
- delete：削除

となっています

商品
一覧取得API get /api/tasks
詳細取得API get /api/tasks/{task_id}
新規作成API post /api/tasks
更新API put /api/tasks/{task_id}
削除API delete /api/tasks/{task_id}

意味としては、詳細、更新、削除は1つのtaskに対して行うのでエンドポイントは
/api/tasks/{task_id}
のようにid指定した形になります

作成や一覧はtaskを固定する必要がないため、エンドポイントは
/api/tasks
のようにidは指定しない形になります

**Comment by Tamm2** [comment]
**参考になるもの**
ユーザーの新規登録API
ユーザー情報取得API(me api)
というのは、どうやって参照すれば良いのでしょうか。

**Comment by campbel2525** [comment]
@Tamm2 
https://github.com/Tamm2/hello_fastapi2/blob/master/apps/user-api/app/routers/account_routers.py

こちらです

**Comment by campbel2525** [comment]
@Tamm2 

>1

承知しました
手順をissueに詳しく書きます

>2
前回のレビューで発見できなく申し訳ないです

apps/user-api/app/models/orders.py
のファイルは必要ないので削除

apps/user-api/app/models/tasks.py
```
from common.database.model_mixins.user_mixins import TaskMixin
```
ではなく
```
from common.database.model_mixins.task_mixins import TaskMixin
```
ですね


[その他]
1
https://github.com/campbel2525/fastapi-sample/blob/main/common/database/model_mixins/user_mixins.py
を参考にして下記を追加してください

```
if TYPE_CHECKING:
    from app.models.tasks import Task
```

```
    @declared_attr
    def tasks(cls) -> Mapped["Task"]:
        return relationship("Order", backref="user")
```


2
前回追加してもらったコマンド間違えていました。
申し訳ありません
正しくは下記になりますので修正お願いします。
```
reset: ## DBのリセット
	docker compose -f $(pf) -p $(pn) exec -it user-api pipenv run python app/console/commands/drop_all_tables.py
	docker compose -f $(pf) -p $(pn) exec -it user-api pipenv run alembic upgrade head
	docker compose -f $(pf) -p $(pn) exec -it user-api pipenv run python app/console/commands/seeds.py

migrate: ## マイグレート
	docker compose -f $(pf) -p $(pn) exec -it user-api pipenv run alembic revision --autogenerate -m 'comment'
	docker compose -f $(pf) -p $(pn) exec -it user-api pipenv run alembic upgrade head
```

**Comment by campbel2525** [comment]
# WIPです　途中ですので作業はしないようにお願いします


# 細かな手順

## 1 routerを作る

**Comment by Tamm2** [comment]
task_requests.pyについて、account_requests.pyを参考に

```
class CreateReuest(BaseModel):
    title: str = Field()
    content: str = Field()
    deadline_at: datetime = Field()
```

まで書いてみたのですが、ここから先がわかりませんでした。

```
title: 必須、255文字まで
content: 必須、2000文字まで
deadline_at: 必須、日時形式
```

のバリデーションはどのように書くことができますか。

**Comment by campbel2525** [comment]
@Tamm2 
あまり教えると答えになってしまうので、自分で調べてみて欲しいです
初めてだと思うので結構時間がかかってもいいと思います

他に参考になるものとしては
- fastapiの公式サイト
- バリデーションではpydanticを使用していますので、chatgptなどでpydanticについて聞いてみ流のもありです

**Comment by Tamm2** [comment]
了解しました。
ひとまず、以下のコードを書いてみました。

from pydantic import BaseModel, Field
from datetime import datetime

class CreateRequest(BaseModel):
    title: str = Field(max_length=255, description="必須、255文字まで")
    content: str = Field(max_length=2000, description="必須、2000文字まで")
    deadline_at: datetime = Field(description="必須、日時形式")

**Comment by Tamm2** [comment]
@campbel2525 

`make check`を実行しようとすると
```
docker compose -f "./docker/docker-compose.yml" -p "python-sample" exec -it user-api pipenv run isort .
service "user-api" is not running
make: *** [check] Error 1
```
とエラーになってしまいました。
昨日は無事に実行できたのですが・・・

そこで、`make user-api run`を実行すると、
`make: *** No rule to make target `user-api'.  Stop.`
と出てしまいました。

このエラーは解決することができるのでしょうか。

**Comment by Tamm2** [comment]
なかなか難しく、また先が遠いように感じます。
@campbel2525 さんは、どのようにしてプログラミングを勉強されてきましたか？
よかったら聞かせていただけると嬉しいです！

**Comment by campbel2525** [comment]
>なかなか難しく、また先が遠いように感じます。

初めてなので全然時間かかっていいと思いますよ！
今回は参考になるユーザー系のapiがあるので、真似しながら進めればいいと思います！
参考なるものが何もないと、全く進まず止まってしまうことは結構あると思います


> どのようにしてプログラミングを勉強されてきましたか？

僕のおすすめの勉強法としては「実際に動くプログラムをいじりながら作業」するのが一番いいと思います
今回は共有したプログラムをいじりながらやるのがいいと思っています

僕が初めてフレームワークを触る場合はまずは、
- 公式サイトのチュートリアルを見る(やる)
  - fastapiのチュートリアルはあまり良くない気がしています
- 参考になる書籍や参考になる動画を見る

ですかね

**Comment by campbel2525** [comment]
もし難しければ、ユーザー側の修正やってみますか？

元ユーザーは
名前とemailとパスワードしかないので、練習がてら項目を増やしてm流のもいいと思います！

**Comment by campbel2525** [comment]
@Tamm2 

https://github.com/Tamm2/hello_fastapi2/issues/19
こちら作ったのでこちらからやってみましょうか！

**Comment by Tamm2** [comment]
ありがとうございます！

実は、先のコメントにも書いた通り、まずmake checkが実行できなってしまいました。

再度実行してみても、
```

Loading .env environment variables...
./app/routers/task_routers.py:1:2: F821 undefined name 'router'
./app/routers/task_routers.py:3:20: F821 undefined name 'task_responses'
./app/routers/task_routers.py:4:17: F821 undefined name 'swagger_configs'
./app/routers/task_routers.py:5:21: F821 undefined name 'swagger_configs'
./app/routers/task_routers.py:6:15: F821 undefined name 'swagger_configs'
./app/routers/task_routers.py:9:14: F821 undefined name 'task_requests'
./app/routers/task_routers.py:10:9: F821 undefined name 'Session'
./app/routers/task_routers.py:10:19: F821 undefined name 'Depends'
./app/routers/task_routers.py:10:27: F821 undefined name 'settings'
./app/routers/task_routers.py:11:6: F821 undefined name 'task_responses'
./app/routers/task_routers.py:16:12: F821 undefined name 'models'
./app/routers/task_routers.py:28:12: F821 undefined name 'task_responses'
./app/routers/task_routers.py:28:55: F821 undefined name 'auth_user'
make: *** [check] Error 1
```
でした。
これをまず解決できたらなと思うのですが、何かいいアイデアはないでしょうか。

**Comment by campbel2525** [comment]
> これをまず解決できたらなと思うのですが、何かいいアイデアはないでしょうか。

今回の修正文が悪さをしていると思います
こういう時の手順は、どの修正がエラーになっているのかの洗い出しを行うといいです

1
mainブランチではエラーにならないことを確認する

2
今回の修正分を確認する
コード上で確認するのは難しいため、プルリクを作ってgithubを見ながら探す


こんな感じで進めればいいと思いますよ！

**Comment by campbel2525** [comment]
https://github.com/Tamm2/hello_fastapi2/issues/10#issuecomment-2041342353

ちなみにこのエラーはdockerが立ち上がっていませんね
なのでmake upすればいいと思います

上記のエラーは不明です

**Comment by Tamm2** [comment]
実はmainブランチでもエラーになってしまうんです。

**Comment by campbel2525** [comment]
僕の方では下記のエラーが出ました
```
./app/schemas/responses/account_responses.py:1:1: F401 'pydantic.ConfigDict' imported but unused
```

https://github.com/Tamm2/hello_fastapi2/issues/10#issuecomment-2041768797
このエラーは出ませんね

**Comment by campbel2525** [comment]
@Tamm2 
僕の方ではエラーは出ませんでした
https://github.com/Tamm2/hello_fastapi2/issues/10#issuecomment-2041768797
とは違うエラーが出たのですが、`make init`で作り直したらエラーが出なくなりました


下記の対応をするといいかもですね
やってみること
- 最新の`main`かどうか
  - `git switch main`
  - `git pull origin main`
- dockerは立ち上がっているかどうか
  - `make up`コマンドを実行する
- dockerを再起動後に`make up`
- 再度docker環境を作り直す
  - `make destroy`
  - `make init`
- mainブランチに変な差分がないかどうか
  - `git log`

**Comment by Tamm2** [comment]
@campbel2525 
git pull origin mainを実行したのですが、
```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

となってしまいました。
ただ、このエラーからどこが悪いのかがわかりません。
こういう時は、どうすれば良いのでしょうか。

**Comment by Tamm2** [comment]
@campbel2525 
orders.pyを復活させたらgit pull origin mainを実行できました。
ただ、このファイルは不要なはずで、これを削除しつつgit pull origin mainを実行できるようにしなければならないのでしょうか。

**Comment by Tamm2** [comment]
make initはうまく実行できて、
make checkを実行すると

```
app/models/orders.py:1: error: Skipping analyzing "common.database.model_mixins.order_mixins": module is installed, but missing library stubs or py.typed marker  [import-untyped]
app/models/orders.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 49 source files)
make: *** [check] Error 1
```
というエラーが出ました。
orders.pyが悪さをしているのですが、これを削除するとgit pull origin mainが出来なくならないか怖くて出来ていません。
git pull origin mainを実行した後であれば削除してもいいものなのでしょうか。

**Comment by campbel2525** [comment]
今はどのブランチで作業していますか？

`git branch`で確認ができます

**Comment by campbel2525** [comment]
mainブランチですかね？
mainブランチで作業していないはずなので、mainブランチでは差分はないはずです
もし差分があるようならば、差分を無くした方がいいです

色々方法があると思うのですが、commitしている場合、commitしていない場合などで対応が変わるため、確認など色々面倒なので以下のコマンドでmainブランチをリセットしましょうか

下記のコマンド通りにやればmainブランチをリモートのmainブランチに合わせることが可能です
```
git add .
git commit -m 'aaa'
git switch -c temp
git breanch -D main
git fetch 
git switch main
```
