### ISSUE TITLE
ユーザー登録で項目を増やす

### ISSUE THREAD

**Issue by campbel2525** [Tamm2/hello_fastapi2#19]
# タスクのゴール

ユーザー登録apiでtelを保存できるようにする

# 作業内容
1
usersテーブルに
tel, 電話番号,string(15), nullable
を追加する

具体的にはmixinに追加後にmake migrateを実行する

2
ユーザー登録apiのバリデーションにtelの項目を追加する
他の項目についても文字数のバリデーションを入れる

3
DBに登録している処理でtelを追加すること

4
swaggerで動作確認を行うこと

# 参考
ユーザー系のルーターは下記になります
https://github.com/Tamm2/hello_fastapi2/blob/main/apps/user-api/app/routers/account_routers.py

**Comment by campbel2525** [comment]
>3.はどのファイルを指しているのでしょうか。

https://github.com/Tamm2/hello_fastapi2/blob/main/apps/user-api/app/routers/account_routers.py
のsign_up()です

**Comment by Tamm2** [comment]
正解がわからなくて、わからないなりに予想でプッシュしてプルリクを作ってみたのですが、その場合、次にどうすべきか教えていただけるでしょうか。
正直、時間をかけても自分一人では永遠に正解に辿り着ける気がしません

**Comment by campbel2525** [comment]
- https://github.com/Tamm2/hello_fastapi2/pull/24

こちらレビューして大丈夫ですかね？

**Comment by Tamm2** [comment]
お願いします！

**Comment by campbel2525** [comment]
@Tamm2 
一通りコメントしました

**Comment by Tamm2** [comment]
@campbel2525 ありがとうございます！
