### ISSUE TITLE
me apiでレスポンスの項目を増やす

### ISSUE THREAD

**Issue by campbel2525** [Tamm2/hello_fastapi2#20]
# タスクのゴール

me apiでレスポンスの項目を増やす

# 作業内容
1
me apiのレスポンスのファイルを修正して、telを返すようする

3
swaggerで動作確認を行うこと

# 参考
ユーザー系のルーターは下記になります
https://github.com/Tamm2/hello_fastapi2/blob/main/apps/user-api/app/routers/account_routers.py

**Comment by Tamm2** [comment]
1
me apiのレスポンスのファイルを修正して、telを返すよううする

はどのファイルを指しているのでしょうか。

**Comment by campbel2525** [comment]
こちらのme()になります！
https://github.com/Tamm2/hello_fastapi2/blob/main/apps/user-api/app/routers/account_routers.py
